---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/cwb124/tutorial.git
      branch: master
jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: tutorial
      - task: hello-world
        file: tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
  - name: job-test-add
    public: true
    plan:
      - get: tutorial
      - task: test-add
        file: tutorial/tutorials/basic/temp/test.yml